#!/bin/bash

echo $COMSPEC | grep WINDOWS > /dev/null
IS_NOT_WINDOWS=$?
ROOT_DIR=`pwd`

if (($IS_NOT_WINDOWS))
then cd build &&         make debug && cd bin/Debug/ && gdb ./loopidity-dbg
else cd build && MINGW=1 make debug && cd bin/Debug/ && gdb ./loopidity-dbg.exe
fi
cd $ROOT_DIR
