.\" Manpage for Loopidity
.TH Loopidity 1 "12 Jul 2017" "loopidity v0.14" "Loopidity Man Page"
.SH NAME
Loopidity \- A multi-track, multi-channel, looping audio recorder
            designed for live hands-free use
.SH SYNOPSIS
.nf
\fIloopidity\fR
.SH DESCRIPTION
.nh
Loopidity is a native GNU/Linux and Windows application built with
the SDL framework and using the JACK Connection Kit for audio I/O.
Loopidity can record multiple sets of multi-channel audio tracks
and is designed so that the most useful functions can be controlled
using as few buttons as possible (a small number of foot pedals for example).
.SH OPTIONS
Loopidity currently has no command-line options.
.SH BUGS
See https://github.com/bill-auger/loopidity/issues.
.SH AUTHOR
bill-auger <bill-auger@programmer.net>
